### ISSUE TITLE
在RIME上使用行列的問題

### ISSUE THREAD

**Issue by archerindigo** [rime/rime-array#1]
試用了rime的行列輸入法一段時間，感覺rime的輸入介面比較舒服，連打功能亦頗為方便，但同時有很多行列輸入法的功能都無法實現，以致輸入上諸多不便，尤其是以下幾個基本功能：

- 無法使用簡碼
    - 例如"為“有一級簡碼"6- 9" (h9)和二級簡碼"6- 9- 9" (hl9)，但都無法打出
    - rime的候選字沒有指定排序，或許是簡碼無法實現的原因

- 無法輸入標點符號
    - 行列本身在"3-" (d)、 "0v" (/)以及”2^ + 數字“ (w + 數字)定義了各種標點符號，但在rime-array都無法打出

- 無萬用字元( * 及 ? )

未是以上缺撼是否rime引擎本身限制所致，希望儘可能改善

**Comment by lotem** [comment]
可以肯定「萬用字元」是引擎尚未支持的特性。
至於簡碼和標點符號，並沒有限制使用，應當是碼表未收錄這些碼。
這份碼表是使用行列輸入法的網友提供，沒有專人維護。如果題主有辦法根據權威的資料完善這份碼表，那是最好的。

**Comment by archerindigo** [comment]
簡碼的特別之處是它在候選字列表中有特定的位置，剛實驗了一下，是可以將簡碼略去數字加到碼表，再在同碼字中滲入一些無效的字符補位實現。不過之後候選字排序又會因為字詞輸入頻率而被調動...

3- 和 0v 的標點符號也是可以透過修改字碼表實現，不過w + 數字的標點符號是需要開新選單供人選擇，這個未知如何做。 

權威的字碼表我可以找老刀看看，以我所知他是近年最積極維護行列字碼表的網友，gcin等他都有提供字碼表。
